### PR TITLE
Several changes to syntax highlighting

### PR DESCRIPTION
**Pull request by MattDMo**
First, I made a few changes to the Sublime Text Syntax Def (YAML) files to fix a couple of bugs and add highlighting for the `author`, `bundleUUID`, `firstLineMatch`, `foldingStartMarker`, `foldingStopMarker`, and `keyEquivalent` fields.

From:

before

To:

after

---

Second, I fixed a bug in the Sublime Key Map files that didn't highlight escapes in strings, and also didn't interpret `\\` at the end of a string correctly, breaking highlighting. Here's an example from the keymap from Vintageous:

old behavior

and here it is fixed:

fixed

The color scheme is my [`Neon Color Scheme`](https://packagecontrol.io/packages/Neon%20Color%20Scheme), which I've customized to include a bunch of AAAPackageDev scopes.

### CODE REVIEW

**Comment by MattDMo** [comment]
First, I made a few changes to the Sublime Text Syntax Def (YAML) files to fix a couple of bugs and add highlighting for the `author`, `bundleUUID`, `firstLineMatch`, `foldingStartMarker`, `foldingStopMarker`, and `keyEquivalent` fields.

From:

before

To:

after

---

Second, I fixed a bug in the Sublime Key Map files that didn't highlight escapes in strings, and also didn't interpret `\\` at the end of a string correctly, breaking highlighting. Here's an example from the keymap from Vintageous:

old behavior

and here it is fixed:

fixed

The color scheme is my [`Neon Color Scheme`](https://packagecontrol.io/packages/Neon%20Color%20Scheme), which I've customized to include a bunch of AAAPackageDev scopes.

**Comment by FichteFoll** [comment]
Thank you for the contribution.

Just to let you know, I won't have time to review this in the next maybe two weeks.

**Comment by MattDMo** [comment]
OK, no problem.

**Comment by FichteFoll** [comment]
Thanks, I've cherry-picked most commits.

The escaped character in key maps was already fixed in master.

Seeing the Key Map syntax def was a truly horrendous experience though. I attempted to do it somewhat properly at first, but it is so fundamentally flawed that rewriting it completely seems like the only option. And I intend to do that anyway.

I'll probably allocate some time for the long-needed PackageDev overhaul on the next weekend.

**Pull request closed without merging**
